jobs:
- job: Build
  pool:
    vmImage: ubuntu-latest
  steps:
  - task: UseNode@1
    inputs:
      version: '22.x'

  - task: Npm@1
    displayName: npm ci
    inputs:
      command: ci

  - script: npm test
    displayName: npm test
    env:
      CI: 'true'

  - task: PublishTestResults@2
    displayName: Publish test results
    condition: succeededOrFailed()
    inputs:
      testResultsFormat: 'JUnit'
      testResultsFiles: 'test-results/*.xml'
      testRunTitle: 'Unit tests'
      failTaskOnFailedTests: true

  - script: npm run build
    displayName: npm run build

  - task: TfxInstaller@5
    condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
    inputs:
      version: 'v0.x'

  - task: PackageAzureDevOpsExtension@5
    displayName: Package (dev)
    condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
    inputs:
      rootFolder: '$(sourceDir)'
      patternManifest: |
        vss-extension.json
        src/**/*.manifest.json
      publisherId: '$(publisherId)'
      extensionVersion: '$(Build.BuildNumber)'
      updateTasksVersion: true
      outputPath: '$(extensionId)-dev-$(Build.BuildNumber).vsix'
      arguments: '--overrides-file configs/dev.json --manifest-globs vss-extension.json "src/**/*.manifest.json"'

  - task: PackageAzureDevOpsExtension@5
    displayName: Package (release)
    condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
    inputs:
      rootFolder: '$(sourceDir)'
      patternManifest: |
        vss-extension.json
        src/**/*.manifest.json
      publisherId: '$(publisherId)'
      extensionVersion: '$(Build.BuildNumber)'
      updateTasksVersion: true
      outputPath: '$(extensionId)-$(Build.BuildNumber).vsix'
      arguments: '--overrides-file configs/release.json --manifest-globs vss-extension.json "src/**/*.manifest.json"'

  - task: CopyFiles@2
    condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
    inputs:
      contents: '**/*.vsix'
      targetFolder: '$(Build.ArtifactStagingDirectory)'
      flattenFolders: true

  - task: PublishBuildArtifacts@1
    condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
    inputs:
      pathToPublish: '$(Build.ArtifactStagingDirectory)'
      artifactName: drop
